
""" Plot adiabatic population from an ensemble of ZagHop trajectories. """
import argparse
import os
import numpy as np
import matplotlib.pyplot as plt


def add_subparser(subparsers):
    """ Register the 'population' subcommand under the 'plot' subparser. """
    parser = subparsers.add_parser(
        "population",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description="Plot population from a file generated by 'zagpy ensemble population'.")
    parser.add_argument(
        "file",
        type=str,
        metavar="FILE",
        help="Population file (e.g., pop_adiabatic.dat or pop_diabatic.dat).")
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.03,
        metavar="P",
        help="Skip plotting states whose population never exceeds this value.")
    parser.add_argument(
        "--confidence-interval",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="""Plot confidence intervals if available. Requires files with
          suffixes '.lbound' and '.ubound' containing the lower and upper 
          bounds of the confidence intervals, respectively."""
    )
    parser.add_argument(
        "--save",
        type=str,
        default=None,
        metavar="FILE",
        help="Save the figure to FILE instead of displaying it.")
    parser.add_argument(
        "--labels",
        type=str,
        default=None,
        metavar="FILE",
        help="""File containing labels for each state. Should have one label per line,
          in the same order as the states in the population file.""")
    parser.set_defaults(func=run)


def plot_population(time, pop, ax=None, lbound=None, ubound=None,
                    labels=None, colors=None, threshold=0.03, **kwargs):
    if ax is None:
        ax = plt.subplots()[1]
    if labels is None:
        labels = [f"S$_{{{i+1}}}$" for i in range(pop.shape[1])]
    if colors is None:
        colors = plt.rcParams["axes.prop_cycle"].by_key()["color"]
    line_styles = ['-', '--', '-.', ':']
    for i, state_pop in enumerate(pop.T):
        if np.all(state_pop < threshold):
            continue
        color = colors[i % len(colors)]
        ls = line_styles[(i // len(colors)) % len(line_styles)]
        ax.plot(time, state_pop, ls=ls, c=color, label=labels[i], **kwargs)
        if lbound is not None and ubound is not None:
            ax.fill_between(time, lbound[:, i], ubound[:, i], color=color, alpha=0.2)
    ax.legend(frameon=False)
    ax.set_xlabel("Time / fs")
    ax.set_ylabel("Population")
    ax.set_ylim([0, 1])
    return ax


def run(args):
    data = np.loadtxt(args.file)
    time = data[:, 0]
    pop = data[:, 1:]
    lbound = None
    ubound = None
    if args.confidence_interval:
        cdir = os.path.dirname(args.file)
        cfile, cext = os.path.splitext(os.path.basename(args.file))
        lbound = np.loadtxt(os.path.join(cdir, f"{cfile}_lbound{cext}"))[:, 1:]
        ubound = np.loadtxt(os.path.join(cdir, f"{cfile}_ubound{cext}"))[:, 1:]
    labels = None
    if args.labels is not None:
        with open(args.labels, "r") as f:
            labels = [line.strip() for line in f]
        if len(labels) != pop.shape[1]:
            raise ValueError("Number of labels does not match number of states.")
    _, ax = plt.subplots()
    plot_population(time, pop, ax=ax, lbound=lbound, ubound=ubound,
                   labels=labels, threshold=args.threshold)
    if args.save:
        plt.savefig(args.save)
    else:
        plt.show()
