name: CI

on: 
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libblas-dev liblapack-dev
      - name: Run CMake
        run: cmake --preset release
      - name: Build
        run: cmake --build --preset release
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
      - name: Run ZagHop Tests
        working-directory: ./build/release
        run: ctest
